### ISSUE TITLE
(Java/Processing) install link giving 404 error

### ISSUE THREAD

**Issue by QuentinRomeroLauro** [berry-cs/sinbad#19]
Following [this](https://berry-cs.github.io/sinbad/install-java) link, the [https://cs.berry.edu/sinbad/index-java.php](http://cs.berry.edu/sinbad/index-java.php) link found under the **Quick Install** section gives a 404 Error.

**Comment by nadeemabdulhamid** [comment]
OK, that should get updated when GIthub rebuilds the page. The correct link with https should work:  https://cs.berry.edu/sinbad/index-java.php 
Thank you!
